//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 02:38:29 PM CET 
//


package SC13Project.Milestone1.BookStore.JaxbComponent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the SC13Project.Milestone1.BookStore.DataBase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Category_QNAME = new QName("http://www.example.org/BookCategoryDB", "category");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: SC13Project.Milestone1.BookStore.DataBase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategoryInfo }
     * 
     */
    public CategoryInfo createCategoryInfo() {
        return new CategoryInfo();
    }

    /**
     * Create an instance of {@link BookInfo }
     * 
     */
    public BookInfo createBookInfo() {
        return new BookInfo();
    }

    /**
     * Create an instance of {@link AuthorsInfo }
     * 
     */
    public AuthorsInfo createAuthorsInfo() {
        return new AuthorsInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/BookCategoryDB", name = "category")
    public JAXBElement<CategoryInfo> createCategory(CategoryInfo value) {
        return new JAXBElement<CategoryInfo>(_Category_QNAME, CategoryInfo.class, null, value);
    }

}
